/**
 * PassportIssuer tests. Port of Python test_issuer.py (8 tests).
 *
 * Test 8 is the cross-backend signature parity fixture — proves the TS
 * canonicalize + sign primitives produce byte-identical output to the
 * backend's `json-canonicalize` + `@noble/ed25519`. Fixture constants are
 * byte-copied from python/tests/passport/test_issuer.py lines 136-169.
 *
 * Three-way parity chain (backend ↔ Python ↔ TS):
 * - Backend generated the constants via scripts/sdk_parity_fixture.ts
 * - Python test hard-codes them at test_issuer.py:136-169
 * - TS test hard-codes the same literals here
 * Any drift triggers a release-blocker condition per spec §11.2, §13 row 26.
 */

import { bytesToHex } from '@noble/hashes/utils.js';
import * as ed from '@noble/ed25519';
import { describe, expect, it } from 'vitest';

import { AgentCredentials } from '../src/passport/credentials.js';
import { canonicalizeStrict } from '../src/passport/canonical.js';
import type { Envelope } from '../src/passport/envelope.js';
import { PassportIssuer } from '../src/passport/issuer.js';
import { TrustTier } from '../src/passport/tier.js';
import { PassportVerifier } from '../src/passport/verifier.js';

function issue(opts: {
  identityClaim?: string | null;
  permissions?: Array<{ permission_key: string; constraints?: Record<string, unknown> }>;
  expiresAt?: Date;
  delegationAuthority?: boolean;
} = {}): { env: Envelope; sig: string; creds: AgentCredentials } {
  const creds = AgentCredentials.generate();
  const issuer = new PassportIssuer(creds, { identityClaim: opts.identityClaim ?? 'alice@dev.local' });
  const { envelope, signature } = issuer.selfIssue({
    permissions: opts.permissions ?? [{ permission_key: 'api:read', constraints: {} }],
    expiresAt: opts.expiresAt ?? new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    delegationAuthority: opts.delegationAuthority,
  });
  return { env: envelope, sig: signature, creds };
}

describe('PassportIssuer.selfIssue', () => {
  it('produces a valid envelope shape', () => {
    const { env, sig } = issue();
    expect(env.schema_version).toBe(2);
    expect(env.passport_id).toMatch(/^pp_self_[0-9a-f]{32}$/);
    expect(env.provenance.issuer.type).toBe('self');
    expect(env.provenance.issuer.key_id).toBe('self');
    expect(env.provenance.delegation_chain).toBeNull();
    expect(env.provenance.gate_id).toBeNull();
    expect(env.provenance.catalog_content_hash).toBeNull();
    expect(env.provenance.catalog_version).toBeNull();
    expect(env.verification_evidence).toEqual([]);
    expect(Buffer.from(sig, 'base64')).toHaveLength(64);
  });

  it('agent_id and public_key match credentials', () => {
    const { env, creds } = issue();
    expect(env.identity.agent_id).toBe(creds.agentId);
    expect(env.identity.public_key).toBe(Buffer.from(creds.publicKey).toString('base64'));
  });

  it("issuer.id = 'self:' + sha256(pubkey).hex", async () => {
    const { sha256 } = await import('@noble/hashes/sha2.js');
    const { env, creds } = issue();
    const expected = 'self:' + bytesToHex(sha256(creds.publicKey));
    expect(env.provenance.issuer.id).toBe(expected);
  });

  it('expires_at honors the provided absolute timestamp', () => {
    const expiresAt = new Date('2026-05-22T00:00:00.000Z');
    const { env } = issue({ expiresAt });
    expect(env.provenance.expires_at).toBe('2026-05-22T00:00:00.000Z');
  });

  it('delegation_authority defaults to false', () => {
    const { env } = issue();
    expect(env.delegation_authority).toBe(false);
  });

  it('delegation_authority is true when set', () => {
    const { env } = issue({ delegationAuthority: true });
    expect(env.delegation_authority).toBe(true);
  });

  it('identityClaim=null produces agent_name=null and still verifies locally', () => {
    const creds = AgentCredentials.generate();
    const issuer = new PassportIssuer(creds, { identityClaim: null });
    const { envelope, signature } = issuer.selfIssue({
      permissions: [{ permission_key: 'api:read', constraints: {} }],
      expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
    });
    expect(envelope.identity.agent_name).toBeNull();

    const result = new PassportVerifier().verify(envelope, signature);
    expect(result.valid).toBe(true);
    if (result.valid) expect(result.tier).toBe(TrustTier.L0);
  });
});

// ---------------------------------------------------------------------------
// Cross-backend signature parity fixture.
// ---------------------------------------------------------------------------
//
// Ground-truth constants generated by the backend's
// ~/Projects/modei/scripts/sdk_parity_fixture.ts and byte-copied here from
// python/tests/passport/test_issuer.py:136-169. Deterministic: 32-byte zero
// Ed25519 seed + fixed timestamps + fixed passport_id → reproducible sig.
//
// If this test fails, STOP. Either the canonicalizer or the signer drifted
// from backend parity — release-blocker per spec §11.2, §13 row 23/26.

const FIXTURE_PUB_B64 = 'O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik=';
const FIXTURE_PRIV_SEED = new Uint8Array(32); // 32 zero bytes
const FIXTURE_AGENT_ID = 'agent_self_E545QOZLVJFyIIjZoNdBYo_IJuCUddNB';
const FIXTURE_ISSUER_ID = 'self:139e3940e64b5491722088d9a0d741628fc826e09475d341a780acde3c4b8070';
const FIXTURE_ISSUED_AT = '2026-04-22T00:00:00.000Z';
const FIXTURE_EXPIRES_AT = '2026-05-22T00:00:00.000Z';
const FIXTURE_PASSPORT_ID = 'pp_self_fixture_00000001';
const FIXTURE_AGENT_NAME = 'fixture@dev.local';
const FIXTURE_SIGNATURE_B64 =
  'KGMwOp9+holhnLRlZwLpUardsQx2E+QWGT2/q27OrfGieXpFEA705UTkLs1hAYd3OkB9/6DuGVI2VfV9iYSHDA==';
const FIXTURE_CANONICAL_HEX =
  '7b2264656c65676174696f6e5f617574686f72697479223a66616c73652c22696465' +
  '6e74697479223a7b226167656e745f6964223a226167656e745f73656c665f453534' +
  '35514f5a4c564a467949496a5a6f4e6442596f5f494a75435564644e42222c226167' +
  '656e745f6e616d65223a2266697874757265406465762e6c6f63616c222c22707562' +
  '6c69635f6b6579223a224f326f6e764d3632704331696f366a514b6d384e63325579' +
  '46586364346b4f6d4f7342496f59745a32696b3d227d2c2270617373706f72745f69' +
  '64223a2270705f73656c665f666978747572655f3030303030303031222c22706572' +
  '6d697373696f6e73223a5b7b22636f6e73747261696e7473223a7b7d2c227065726d' +
  '697373696f6e5f6b6579223a226170693a72656164227d5d2c2270726f76656e616e' +
  '6365223a7b22636174616c6f675f636f6e74656e745f68617368223a6e756c6c2c22' +
  '636174616c6f675f76657273696f6e223a6e756c6c2c2264656c65676174696f6e5f' +
  '636861696e223a6e756c6c2c22657870697265735f6174223a22323032362d30352d' +
  '32325430303a30303a30302e3030305a222c22676174655f6964223a6e756c6c2c22' +
  '6973737565645f6174223a22323032362d30342d32325430303a30303a30302e3030' +
  '305a222c22697373756572223a7b226964223a2273656c663a313339653339343065' +
  '36346235343931373232303838643961306437343136323866633832366530393437' +
  '356433343161373830616364653363346238303730222c226b65795f6964223a2273' +
  '656c66222c2274797065223a2273656c66227d7d2c22736368656d615f7665727369' +
  '6f6e223a322c22766572696669636174696f6e5f65766964656e6365223a5b5d7d';

describe('cross-backend signature parity', () => {
  it('matches backend canonical bytes + signature for self-issued fixture', () => {
    const env: Envelope = {
      schema_version: 2,
      passport_id: FIXTURE_PASSPORT_ID,
      identity: {
        agent_id: FIXTURE_AGENT_ID,
        agent_name: FIXTURE_AGENT_NAME,
        public_key: FIXTURE_PUB_B64,
      },
      permissions: [{ permission_key: 'api:read', constraints: {} }],
      provenance: {
        issuer: { type: 'self', id: FIXTURE_ISSUER_ID, key_id: 'self' },
        gate_id: null,
        catalog_content_hash: null,
        catalog_version: null,
        delegation_chain: null,
        issued_at: FIXTURE_ISSUED_AT,
        expires_at: FIXTURE_EXPIRES_AT,
      },
      delegation_authority: false,
      verification_evidence: [],
    };

    // (a) Canonical bytes assertion runs BEFORE the signature assertion: on
    // failure, the hex diff shows exactly which envelope bytes drifted.
    const canonical = canonicalizeStrict(env);
    expect(Buffer.from(canonical).toString('hex')).toBe(FIXTURE_CANONICAL_HEX);

    // (b) Ed25519 sign is deterministic; any drift is a release-blocker.
    const sigBytes = ed.sign(canonical, FIXTURE_PRIV_SEED);
    expect(Buffer.from(sigBytes).toString('base64')).toBe(FIXTURE_SIGNATURE_B64);

    // (c) Local round-trip: SDK verifier accepts the backend-matching signature.
    const result = new PassportVerifier().verify(env, FIXTURE_SIGNATURE_B64);
    expect(result.valid).toBe(true);
    if (result.valid) expect(result.tier).toBe(TrustTier.L0);
  });
});
